package com.oneasmr.app.data.local

import androidx.paging.PagingSource
import androidx.room.Room
import com.oneasmr.app.data.scanner.RoomScanPersister
import com.oneasmr.app.data.scanner.WorkCandidate
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.RuntimeEnvironment
import org.robolectric.annotation.Config

/**
 * Task 12: the REAL Room PagingSource (LimitOffsetPagingSource — a single
 * `LIMIT ? OFFSET ?` query per page, generated by Room; see WorkDao_Impl).
 * Loads are exercised directly with suspend load() calls (no Pager, no
 * dispatcher gymnastics): page slicing, prev/next keys, join fields, and
 * invalidation mechanics. No full-table materialization is possible by
 * construction — the query itself is offset-limited.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
class WorkDaoPagingSourceTest {

    private lateinit var db: OneAsmrDatabase

    @Before
    fun setUp() {
        db = Room.inMemoryDatabaseBuilder(
            RuntimeEnvironment.getApplication(),
            OneAsmrDatabase::class.java,
        ).build()
    }

    @After
    fun tearDown() {
        db.close()
    }

    private fun commitWork(rjCode: String, rootUri: String = "content://tree/rootA") {
        runBlocking {
            RoomScanPersister(db).commitWork(WorkCandidate(rjCode, rjCode, rjCode), rootUri, 1_000L)
        }
    }

    private suspend fun refreshPage(
        source: PagingSource<Int, WorkListItem>,
        loadSize: Int = 10,
    ): PagingSource.LoadResult.Page<Int, WorkListItem> =
        source.load(PagingSource.LoadParams.Refresh(key = null, loadSize = loadSize, placeholdersEnabled = false))
            as PagingSource.LoadResult.Page<Int, WorkListItem>

    @Test
    fun `refresh returns the first page in deterministic id order with next key`() = runBlocking {
        (1..25).forEach { commitWork("RJ${100000 + it}") }
        val page = refreshPage(db.workDao().pagingSource(), loadSize = 10)
        assertEquals(10, page.data.size)
        assertNull(page.prevKey)
        // Room's LimitOffsetPagingSource keys pages by OFFSET, not index.
        assertEquals(10, page.nextKey)
        assertEquals("local:RJ100001", page.data.first().id)
        assertEquals("local:RJ100010", page.data.last().id)
        assertEquals("RJ100001", page.data.first().rjCode)
    }

    @Test
    fun `walking pages reaches every row with no duplicates`() = runBlocking {
        (1..25).forEach { commitWork("RJ${100000 + it}") }
        val source = db.workDao().pagingSource()
        val seen = mutableSetOf<String>()
        var nextKey: Int? = null
        do {
            val params = if (nextKey == null) {
                PagingSource.LoadParams.Refresh<Int>(null, 10, false)
            } else {
                PagingSource.LoadParams.Append<Int>(nextKey!!, 10, false)
            }
            val result = source.load(params) as PagingSource.LoadResult.Page<Int, WorkListItem>
            result.data.forEach { assertTrue("duplicate ${it.id}", seen.add(it.id)) }
            nextKey = result.nextKey
        } while (nextKey != null)
        assertEquals(25, seen.size)
    }

    @Test
    fun `items carry circle name rating scrape status and progress`() = runBlocking {
        runBlocking {
            db.circleDao().upsertAll(listOf(Circle("社团甲", "社团甲", "shetuanjia")))
        }
        commitWork("RJ100001")
        runBlocking {
            val work = db.workDao().getById("local:RJ100001")!!
            db.workDao().upsert(
                work.copy(
                    circleId = "社团甲",
                    rateAverage2dp = 4.52,
                    scrapeStatus = ScrapeStatus.OK,
                ),
            )
            db.reviewDao().upsert(Review("local:RJ100001", rating = 5, reviewText = null, progress = ProgressState.listened, updatedAt = 1L))
        }
        val page = refreshPage(db.workDao().pagingSource(), loadSize = 10)
        assertEquals(1, page.data.size)
        val item = page.data.single()
        assertEquals("社团甲", item.circleName)
        assertEquals(4.52, item.rateAverage2dp!!, 0.001)
        assertEquals(ScrapeStatus.OK, item.scrapeStatus)
        assertEquals(ProgressState.listened, item.progress)
    }

    @Test
    fun `missing works and no-review works map to their flags`() = runBlocking {
        commitWork("RJ100001")
        commitWork("RJ100002")
        runBlocking {
            db.workDao().upsert(db.workDao().getById("local:RJ100001")!!.copy(missing = true))
        }
        val page = refreshPage(db.workDao().pagingSource(), loadSize = 10)
        val byId = page.data.associateBy { it.id }
        assertTrue(byId.getValue("local:RJ100001").missing)
        assertNull(byId.getValue("local:RJ100001").progress)
        assertTrue(!byId.getValue("local:RJ100002").missing)
        assertNull(byId.getValue("local:RJ100002").progress)
    }

    @Test
    fun `load on an invalidated source returns Invalid`() = runBlocking {
        commitWork("RJ100001")
        val source = db.workDao().pagingSource()
        val first = refreshPage(source, loadSize = 10)
        assertEquals(1, first.data.size)
        source.invalidate()
        val result = source.load(PagingSource.LoadParams.Refresh<Int>(null, 10, false))
        assertTrue(result is PagingSource.LoadResult.Invalid)
    }

    @Test
    fun `a fresh source sees rows written after the old source was created`() = runBlocking {
        val stale = db.workDao().pagingSource()
        assertEquals(0, refreshPage(stale, loadSize = 10).data.size)
        commitWork("RJ100001")
        // Room's invalidation tracker fires on the work table write; a new
        // source (what the Pager creates after invalidation) sees the row.
        val fresh = db.workDao().pagingSource()
        val page = refreshPage(fresh, loadSize = 10)
        assertEquals(1, page.data.size)
        assertNotNull(page.data.first().rootFolderUri)
        assertEquals("RJ100001", page.data.first().relativeDir)
    }
}
